// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nczqdqflvkvlzodeormu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jenFkcWZsdmt2bHpvZGVvcm11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzM2MDgsImV4cCI6MjA3MTQ0OTYwOH0.MabHTemvzz2V6tlLoBrAfvSDyqNH5GNBJ0CGo0GxTJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});